name: woodvision
channels:
  - conda-forge
dependencies:
  - python=3.12
  - streamlit=1.24.0
  - pandas=2.1.1
  - numpy=1.24.4
  - Pillow=10.0.0
  - opencv-python-headless=4.8.0.76
  - plotly=5.17.0
  - deepface=0.0.79
  - tensorflow=2.12.0
  - mediapipe=0.10.8
